apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: sample-admission-validating-webhook.chotot.org
webhooks:
- name: sample-admission-validating-webhook.chotot.org
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
  failurePolicy: Ignore
  clientConfig:
    service:
      name: sample-admission-validating-webhook
      namespace: default
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRREhOcWNQNDVyOFJEQU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05NakF4TWpJeU1URXpPVE15V2hnUE1qSTVOREV3TURjeE1UTTVNekphTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQUs3dlN0ZGJLQ3hNTmoybTVSNzViNDR2WnJVUkNOd0Fia01UUnpEYkMrcU1IL0MrNWJqVmN5K1kKa1R6U2Y5ZnY5VStOaDRiZDkyWFk1YjJXeGpLUnN2VGhVMnJSaEVpdHdxbzZYZ0lWbmpYN2N4QXZaR29FVHpBYQp0YlYwUkFGcEloWFNKK1MrYWU2NnNKTGFQczdveEs1YWRwelZFb3hQeHl6WG5TS1RRRmxyTk83Q0UxMzJCa1J1CjNPUFMzSVpJS203V3h4ZnlBMW0wL1VOZUhpeUtkWVVwdzVGZ00zRFEwSW40T2xzMUxxZGlPUGVVUE5DSnlMTEQKaDhrZ0RtNWx5Tk5yWUJvR203TWd5OTlnTmI4eXovMDQyOWRwbWJIT0lVUm53OE5ub2gyQzRHT1k4Qk5mSkZUaAp5VHFDTHFYSnBINHZvZGxhWkM1bkRIdFdZbkhOOGUwQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCm5xbnhUYlY5UmhDalBDazNlLy9CZjNZSy9PZVdpdUdUdTFCRWVRODh5WGpTajk5L0lOeDAvcENUZVhOUjR4aUwKVzQ5TnYxUmVlWmU0MUp1QTdEendjYkNsdTVBcUJQVXBEYVk5SEt6MVZwNk1ZbkhpOHZjelhtd2xJVHMxaG52QQo3UFExOFV1bnd2cERmR0RkcFlidFdXL2lHNlNjVjNoaUxqS0RINnB3ZkhIVTFhNDF6dzc0OUVsS3JPQWhGaC9mCnpuUEJFaVhhVVNyMERQdGhDa1AxN2gzTW1qMEQ0c283WWtqZlV2NWc5QkNGd3dDNEo1SWRsOHlDNkcybC9uV1IKS2hZYmhXZ0Qrc3lzS0VCaEZHcVhnTHpWZFM5U0EyTXIxR1RvTWRMT0hXSjgwa2Ira0cvSzJaK21FdERhaFltWQpFNmtVY1BHVG5TaFRad082SzUxOVF3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
